---
- hosts: amazon-linux
  vars_prompt:
    - name: my_password2
      prompt: Enter password2
      private: true
  tasks:
    - name: execute the linux commands
      command: hostname -f
      register: cmd_content
    - name: debug statment for OS
      debug:
        msg: "OS family is  {{ ansible_os_family }} so will skip the operating system specified"
    - name: print variables contents
      debug:
        msg: "{{ cmd_content.stdout }}"
      when: cmd_content.stderr  == ""
    - name: print command error if present
      debug:
        msg: "{{ cmd_content.stderr }}"
      when: cmd_content.stderr != ""
    - name: inventory hostname
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
