---
- hosts: amazon-linux
  tasks:
    - name: execute the linux commands
      command: hostname -f
      register: cmd_content
    - name: print variables contents
      debug:
        msg: "{{ cmd_content.stdout }}"
      when: cmd_content.stderr  == ""
    - name: print command error if present
      debug:
        msg: "{{ cmd_content.stderr }}"
      when: cmd_content.stderr != ""
    - name: inventory hostname
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
